=== Dolibarr/dolibarr/dev/setup/codetemplates/codetemplates.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT templates (template+)>
<!ELEMENT template (#PCDATA)>
<!ATTLIST template autoinsert CDATA "">
<!ATTLIST template context CDATA "">
<!ATTLIST template deleted CDATA "">
<!ATTLIST template description CDATA "">
<!ATTLIST template enabled CDATA "">
<!ATTLIST template id CDATA "">
<!ATTLIST template name CDATA "">

=== Dolibarr/dolibarr/dev/setup/codetemplates/codetemplates.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE codetemplates SYSTEM "codetemplates.dtd">
<templates><template autoinsert="true" context="phpcomment" deleted="false" description="Comment for getter methods" enabled="true" id="org.eclipse.php.ui.editor.templates.php.codetemplates.gettercomment" name="gettercomment">/**
 * @return the ${bare_field_name}
 */</template><template autoinsert="true" context="phpcomment" deleted="false" description="Comment for setter methods" enabled="true" id="org.eclipse.php.ui.editor.templates.php.codetemplates.settercomment" name="settercomment">/**
 * @param ${param} the ${bare_field_name} to set
 */</template><template autoinsert="true" context="phpcomment" deleted="false" description="Comment for created constructors" enabled="true" id="org.eclipse.php.ui.editor.templates.php.codetemplates.constructorcomment" name="constructorcomment">/**
 * ${tags}
 */</template><template autoinsert="true" context="phpcomment" deleted="false" description="Comment for created PHP files" enabled="true" id="org.eclipse.php.ui.editor.templates.php.codetemplates.filecomment" name="filecomment">/**
 * 
 */
</template><template autoinsert="true" context="phpcomment" deleted="false" description="Comment for created types" enabled="true" id="org.eclipse.php.ui.editor.templates.php.codetemplates.typecomment" name="typecomment">/**
 * @author ${user}
 *
 * ${tags}
 */</template><template autoinsert="true" context="phpcomment" deleted="false" description="Comment for fields" enabled="true" id="org.eclipse.php.ui.editor.templates.php.codetemplates.fieldcomment" name="fieldcomment">/**
 * @var ${field_type}
 */</template><template autoinsert="true" context="phpcomment" deleted="false" description="Comment for variables" enabled="true" id="org.eclipse.php.ui.editor.templates.php.codetemplates.varcomment" name="fieldcomment">/* @var ${field_type} */</template><template autoinsert="true" context="phpcomment" deleted="false" description="Comment for non-overriding methods" enabled="true" id="org.eclipse.php.ui.editor.templates.php.codetemplates.methodcomment" name="methodcomment">/**
 * ${cursor}${tags}
 */</template><template autoinsert="true" context="phpcomment" deleted="false" description="Comment for overriding methods" enabled="true" id="org.eclipse.php.ui.editor.templates.php.codetemplates.overridecomment" name="overridecomment">/* (non-PHPdoc)
 * ${see_to_overridden}
 */</template><template autoinsert="true" context="phpcomment" deleted="false" description="Comment for delegate methods" enabled="true" id="org.eclipse.php.ui.editor.templates.php.codetemplates.delegatecomment" name="delegatecomment">/**
 * ${tags}
 * ${see_to_target}
 */</template><template autoinsert="false" context="php" deleted="false" description="print an expression" enabled="true" id="org.eclipse.php.ui.editor.templates.php.print" name="pr">print ${};
${cursor}</template><template autoinsert="false" context="php" deleted="false" description="print a string" enabled="true" id="org.eclipse.php.ui.editor.templates.php.print.string" name="prs">print "${}";
${cursor}</template><template autoinsert="false" context="php" deleted="false" description="print with new line" enabled="true" id="org.eclipse.php.ui.editor.templates.php.print.newline" name="prln">print ${}."\n";
${cursor}</template><template autoinsert="false" context="php" deleted="false" description="print a value" enabled="true" id="org.eclipse.php.ui.editor.templates.php.print.variable" name="prv">print("\${dollar}${variable} = ". ${dollar}${variable});
${cursor}</template><template autoinsert="false" context="php" deleted="false" description="prints the current function name" enabled="true" id="org.eclipse.php.ui.editor.templates.php.print.functionName" name="prf">print("${function_container}");
${cursor}</template><template autoinsert="false" context="php" deleted="false" description="prints the current class name" enabled="true" id="org.eclipse.php.ui.editor.templates.php.print.className" name="prc">print("${class_container}");
${cursor}</template><template autoinsert="false" context="php" deleted="false" description="echo a string" enabled="true" id="org.eclipse.php.ui.editor.templates.php.echo" name="eco">echo("${}");
${cursor}</template><template autoinsert="false" context="php" deleted="false" description="iterates an array" enabled="true" id="org.eclipse.php.ui.editor.templates.php.arrayIterator" name="iter">for (${dollar}${number_variable} = 0 ; ${dollar}${number_variable} &lt; count(${dollar}${array_variable}) ; ${dollar}${number_variable}++) {
	${cursor};
}
</template><template autoinsert="false" context="php" deleted="false" description="instanceof statement" enabled="true" id="org.eclipse.php.ui.editor.templates.php.instanceof" name="inst">if (${dollar}${variable} instanceof ${class}) {
	${cursor};
}
</template><template autoinsert="false" context="php" deleted="false" description="for statement" enabled="true" id="org.eclipse.jdt.ui.templates.for" name="for">for (${dollar}${index} = 0; ${dollar}${index} &lt; ${number_variable}; ${dollar}${index}++) {
	${line_selection}${cursor}
}</template><template autoinsert="false" context="php" deleted="false" description="foreach statement" enabled="true" id="org.eclipse.php.ui.editor.templates.php.foreach" name="fore">foreach (${dollar}${array_variable} as ${dollar}${variable}) {
	${cursor};
}
</template><template autoinsert="false" context="php" deleted="false" description="foreach with key statement" enabled="true" id="org.eclipse.php.ui.editor.templates.php.foreachkey" name="forek">foreach (${dollar}${array_variable} as ${dollar}${number_variable} =&gt; ${dollar}${variable}) {
	${cursor};
}
</template><template autoinsert="false" context="php" deleted="false" description="switch statement" enabled="true" id="org.eclipse.php.ui.editor.templates.php.switch" name="swi">switch (${dollar}${variable}) {
	case ${value}:
	${cursor};
	break;
	
	default:
		;
	break;
}
</template><template autoinsert="false" context="php" deleted="false" description="function statement" enabled="true" id="org.eclipse.php.ui.editor.templates.php.fnc" name="fnc">function ${function_name}()
{
	${cursor};
}
</template><template autoinsert="false" context="php" deleted="false" description="function statement" enabled="true" id="org.eclipse.php.ui.editor.templates.php.function" name="function">function ${function_name}()
{
	${cursor};
}
</template><template autoinsert="false" context="php" deleted="false" description="lambda function statement (closure)" enabled="true" id="org.eclipse.php.ui.editor.templates.php.lambda" name="lambda">function (${parameters}) use (${lexical_variables}) {
	${cursor};
}
</template><template autoinsert="false" context="php" deleted="false" description="lambda function statement (closure)" enabled="true" id="org.eclipse.php.ui.editor.templates.php.closure" name="closure">function (${parameters}) use (${lexical_variables}) {
	${cursor};
}
</template><template autoinsert="false" context="php" deleted="false" description="class statement" enabled="true" id="org.eclipse.php.ui.editor.templates.php.cls" name="cls">class ${class_name} 
{
	function ${function_name}() 
    {
		${cursor};
	}
}
</template><template autoinsert="false" context="php" deleted="false" description="class statement" enabled="true" id="org.eclipse.php.ui.editor.templates.php.class" name="class">class ${class_name} 
{
	function ${function_name}() 
    {
		${cursor};
	}
}
</template><template autoinsert="false" context="php" deleted="false" description="if statement" enabled="true" id="org.eclipse.php.ui.editor.templates.php.if" name="if">if (${condition}) 
{
	${cursor};
}
</template><template autoinsert="false" context="php" deleted="false" description="else statement" enabled="true" id="org.eclipse.php.ui.editor.templates.php.else" name="els">else {
	${cursor};
}
</template><template autoinsert="false" context="php" deleted="false" description="elseif statement" enabled="true" id="org.eclipse.php.ui.editor.templates.php.elif" name="elif">elseif (${condition}) {
	${cursor};
}
</template><template autoinsert="false" context="php" deleted="false" description="try catch block" enabled="true" id="org.eclipse.php.ui.editor.templates.php.try" name="try">try {
	${cursor}
} catch (${Exception} ${dollar}e) {
}
</template><template autoinsert="false" context="php" deleted="false" description="while loop" enabled="true" id="org.eclipse.php.ui.editor.templates.php.while" name="while">while (${condition}) {
	${cursor};
}
</template><template autoinsert="false" context="php" deleted="false" description="iterates a directory" enabled="true" id="org.eclipse.php.ui.editor.templates.php.itdir" name="itdir">${dollar}${dirh} = opendir(${dirname});
if (${dollar}${dirh}) {
	while (${dollar}${dir_element} = readdir(${dollar}${dirh})) {
		${cursor};
	}
	unset(${dollar}${dir_element});
	closedir(${dollar}${dirh});
}
</template><template autoinsert="false" context="php" deleted="false" description="mysql_fetch_row() loop" enabled="true" id="org.eclipse.php.ui.editor.templates.php.mySql.fr" name="my_fr">while (${dollar}${row} = mysql_fetch_row(${dollar}${query})) {
	${cursor};
}
</template><template autoinsert="false" context="php" deleted="false" description="mysql_fetch_array() loop" enabled="true" id="org.eclipse.php.ui.editor.templates.php.mySql.fa" name="my_fa">while (${dollar}${row} = mysql_fetch_array(${dollar}${query})) {
	${cursor};
}
</template><template autoinsert="false" context="php" deleted="false" description="mysql_fetch_object() loop" enabled="true" id="org.eclipse.php.ui.editor.templates.php.mySql.fo" name="my_fo">while (${dollar}${row} = mysql_fetch_object(${dollar}${query})) {
	${cursor};
}
</template><template autoinsert="false" context="php" deleted="false" description="Trap code output" enabled="true" id="org.eclipse.php.ui.editor.templates.php.my_gc" name="my_gc">ob_start();
	
${cursor};

${dollar}${contents} = ob_get_contents();
ob_end_clean();
